// FILE: Multiplayer/Client/Sync/QuestSync.cs

using HarmonyLib;
using Multiplayer.API;
using Multiplayer.Common;
using RimWorld;
using RimWorld.QuestGen;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Verse;

namespace Multiplayer.Client
{
    [HarmonyPatch]
    public static class QuestSync
    {
        private static bool isExecutingSyncedQuestGeneration;

        // STEP 1: Intercept the highest-level utility method for generating quests.
        [HarmonyPatch(typeof(QuestUtility), nameof(QuestUtility.GenerateQuestAndMakeAvailable), new Type[] { typeof(QuestScriptDef), typeof(Slate) })]
        static class GenerateQuestAndMakeAvailable_Patch
        {
            static bool Prefix(QuestScriptDef root, Slate vars)
            {
                // If we are already running the synced generation, let it through.
                if (isExecutingSyncedQuestGeneration)
                {
                    return true;
                }

                // If we are a client, block the original call and wait for the host's command.
                if (Multiplayer.Client != null && Multiplayer.LocalServer == null)
                {
                    return false;
                }

                // If we are the host, capture inputs and broadcast them.
                if (Multiplayer.LocalServer != null)
                {
                    // Push the current random state and capture it. This ensures all clients will use it.
                    Rand.PushState();
                    ulong randState = Rand.StateCompressed;

                    // We don't actually generate the quest here on the host initially.
                    // We just capture the inputs and send them to be generated by everyone in sync.

                    byte[] slateData = WriteSlate(vars);

                    // Now, pop the state so the host's game isn't affected by our Push.
                    Rand.PopState();

                    // Call the SyncMethod to have everyone generate the quest.
                    GenerateQuestSynced(root, slateData, randState);

                    // Block the host's original, unsynced execution.
                    return false;
                }

                // Single-player runs as normal.
                return true;
            }
        }

        // STEP 2: The [SyncMethod] that all clients (including host) execute.
        [SyncMethod]
        public static void GenerateQuestSynced(QuestScriptDef root, byte[] slateData, ulong randState)
        {
            Quest generatedQuest = null;
            try
            {
                isExecutingSyncedQuestGeneration = true;

                // Set the RNG to the host's state for this generation block.
                Rand.PushState();
                Rand.StateCompressed = randState;

                Slate slate = ReadSlate(slateData);
                if (slate == null)
                {
                    Log.Error("MP: Failed to deserialize slate for synced quest generation.");
                    return;
                }

                // Now, everyone calls the original game utility to generate the identical quest.
                // This is safe because we flagged `isExecutingSyncedQuestGeneration = true`.
                generatedQuest = QuestUtility.GenerateQuestAndMakeAvailable(root, slate);
            }
            catch (Exception e)
            {
                Log.Error($"MP: Exception during synced quest generation: {e}");
            }
            finally
            {
                Rand.PopState();
                isExecutingSyncedQuestGeneration = false;
            }

            // After generation, the host triggers the letter display for everyone.
            if (Multiplayer.LocalServer != null && generatedQuest != null)
            {
                ShowLetterSynced(generatedQuest.id);
            }
        }

        // STEP 3: Sync the letter display.
        [SyncMethod]
        public static void ShowLetterSynced(int questId)
        {
            Quest quest = Find.QuestManager.QuestsListForReading.FirstOrDefault(q => q.id == questId);
            if (quest != null)
            {
                QuestUtility.SendLetterQuestAvailable(quest);
            }
        }

        #region Slate Serialization

        private static byte[] WriteSlate(Slate slate)
        {
            var varsField = typeof(Slate).GetField("vars", BindingFlags.NonPublic | BindingFlags.Instance);
            var vars = (IDictionary<string, object>)varsField.GetValue(slate);

            List<string> keys = vars.Keys.ToList();
            List<object> values = keys.Select(k => vars[k]).ToList();

            return ScribeUtil.WriteExposable(new SlateVars(keys, values), "slateVars");
        }

        private static Slate ReadSlate(byte[] data)
        {
            var slateVars = ScribeUtil.ReadExposable<SlateVars>(data);
            var slate = new Slate();
            if (slateVars?.keys != null && slateVars.values != null)
            {
                for (int i = 0; i < slateVars.keys.Count; i++)
                {
                    slate.Set(slateVars.keys[i], slateVars.values[i]);
                }
            }
            return slate;
        }

        private class SlateVars : IExposable
        {
            public List<string> keys;
            public List<object> values;

            public SlateVars() { }
            public SlateVars(List<string> keys, List<object> values)
            {
                this.keys = keys;
                this.values = values;
            }

            public void ExposeData()
            {
                Scribe_Collections.Look(ref keys, "keys", LookMode.Value);
                Scribe_Collections.Look(ref values, "values", LookMode.Deep);
            }
        }
        #endregion

        #region Quest Interaction Sync

        [HarmonyPatch(typeof(Quest), nameof(Quest.Accept))]
        static class QuestAccept_Patch
        {
            static bool Prefix(Quest __instance, Pawn by)
            {
                if (Multiplayer.Client != null && !isExecutingSyncedQuestGeneration)
                {
                    SyncQuestAccept(__instance.id, by);
                    return false;
                }
                return true;
            }
        }

        [SyncMethod]
        static void SyncQuestAccept(int questId, Pawn by)
        {
            Quest quest = Find.QuestManager.QuestsListForReading.FirstOrDefault(q => q.id == questId);
            if (quest != null && quest.State == QuestState.NotYetAccepted)
            {
                quest.Accept(by);
            }
        }
        #endregion
    }
}
